# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='admin', max_length=250),
            preserve_default=False,
        ),
    ]
