# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=250)),
                ('car_no', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('from_loc', models.CharField(max_length=250)),
                ('to_loc', models.CharField(max_length=250)),
                ('fare', models.FloatField(default=5.0)),
                ('start_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.User')),
            ],
        ),
    ]
