# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_loc', models.CharField(max_length=250)),
                ('to_loc', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
