# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-17 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_loc', models.CharField(max_length=250)),
                ('to_loc', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Enlist')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.User')),
            ],
        ),
    ]
